### ISSUE TITLE
Error stack trace broken

### ISSUE THREAD

**Issue by enten** [tallesl/node-safe-require#1]
This module [returns "undefined" when a "MODULE_NOT_FOUND" error is thrown](https://github.com/tallesl/node-safe-require/blob/dd4e6fec451bc1000018c8fd9804b7c9536ebd44/index.js#L7).

If a required file exists (A) and this file requires an another file (B) and that file (B) doesn't exists: "undefined" will be returned. 

**This is a wrong behavior  because the file required (A) exists.
So we must throw the error due to an recursive "require" statement.**

I suggest the patch below:
```javascript
// line 7
if (err.code === 'MODULE_NOT_FOUND' && ~err.message.indexOf(path)) return undefined
```

**Comment by tallesl** [comment]
Good catch. Fixed on 1.0.3.
